Repository zendframework/zend-hydrator, pull requests merged in 2018-12, with the labels that each got.

#86 Do not allow direct instantiation of a MapNamingStrategy
  CHANGELOG.md
  docs/book/v3/migration.md
  src/NamingStrategy/MapNamingStrategy.php
  test/NamingStrategy/MapNamingStrategyTest.php
Labels: bug

#83 Move *EnabledInterface definitions to appropriate namespaces
  CHANGELOG.md
  docs/book/v3/filter.md
  docs/book/v3/migration.md
  docs/book/v3/naming-strategy/intro.md
  docs/book/v3/strategy.md
  mkdocs.yml
  src/AbstractHydrator.php
  src/ClassMethods.php
  src/Filter/FilterEnabledInterface.php
  src/NamingStrategy/NamingStrategyEnabledInterface.php
  src/Reflection.php
  src/Strategy/StrategyEnabledInterface.php
Labels: bc break, enhancement

#89 Add the suffix "Hydrator" to all hydrators
  CHANGELOG.md
  docs/book/v3/filter.md
  docs/book/v3/migration.md
  docs/book/v3/naming-strategy/composite-naming-strategy.md
  docs/book/v3/naming-strategy/identity-naming-strategy.md
  docs/book/v3/naming-strategy/map-naming-strategy.md
  docs/book/v3/naming-strategy/underscore-naming-strategy.md
  docs/book/v3/quick-start.md
  docs/book/v3/strategy.md
  src/ArraySerializable.php
  src/ArraySerializableHydrator.php
  src/ClassMethods.php
  src/ClassMethodsHydrator.php
  src/HydratorPluginManager.php
  src/ObjectProperty.php
  src/ObjectPropertyHydrator.php
  src/Reflection.php
  src/ReflectionHydrator.php
  test/Aggregate/AggregateHydratorFunctionalTest.php
  test/ArraySerializableHydratorTest.php
  test/ClassMethodsHydratorTest.php
  test/HydratorClosureStrategyTest.php
  test/HydratorObjectPropertyTest.php
  test/HydratorPluginManagerFactoryTest.php
  test/HydratorStrategyTest.php
  test/HydratorTest.php
  test/Iterator/HydratingArrayIteratorTest.php
  test/Iterator/HydratingIteratorIteratorTest.php
  test/ObjectPropertyHydratorTest.php
  test/ReflectionHydratorTest.php
  test/Strategy/CollectionStrategyTest.php
Labels: bc break, enhancement

#87 Provide a standalone plugin manager implementation
  CHANGELOG.md
  docs/book/v3/migration.md
  docs/book/v3/plugin-managers.md
  mkdocs.yml
  src/ConfigProvider.php
  src/DelegatingHydratorFactory.php
  src/Exception/MissingHydratorServiceException.php
  src/HydratorPluginManager.php
  src/HydratorPluginManagerFactory.php
  src/HydratorPluginManagerInterface.php
  src/StandaloneHydratorPluginManager.php
  src/StandaloneHydratorPluginManagerFactory.php
  test/StandaloneHydratorPluginManagerFactoryTest.php
  test/StandaloneHydratorPluginManagerTest.php
Labels: bc break, enhancement

#91 Removed unused import and added missing function import
  src/AbstractHydrator.php
  src/ConfigProvider.php
Labels: enhancement

#90 Added Zend\Hydrator\Strategy\DateTimeFormatterStrategy docs
  docs/book/v3/strategy.md
Labels: documentation
